<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Gmail.v1" Version="1.74.0.4148" />
    <PackageReference Include="Google.Apis.Drive.v3" Version="1.74.0.4135" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\printingshop.application\printingshop.application.csproj" />
    <ProjectReference Include="..\printingshop.persistence\printingshop.persistence.csproj" />
  </ItemGroup>

</Project>
